# Generated by Django 4.2.3 on 2023-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkpost',
            name='subject',
            field=models.CharField(default='General', max_length=200),
        ),
    ]
