# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_homeworkpost_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkpost',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
