# Generated by Django 4.2.3 on 2023-07-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_homeworkpost_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkpost',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Completed'), ('No', 'Not-Completed')], default='Not-Completed', max_length=5),
        ),
    ]
