# Generated by Django 4.2.3 on 2023-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_homeworkpost_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkpost',
            name='completed',
        ),
    ]
