# Generated by Django 4.2.3 on 2023-07-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_homeworkpost_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkpost',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
