# Generated by Django 4.2.3 on 2023-07-31 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_homeworkpost_assigned_by_homeworkpost_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpost',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='assigned_to',
            field=models.ManyToManyField(related_name='give_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='related_file',
            field=models.FileField(null=True, upload_to='../media/uploads'),
        ),
        migrations.AddField(
            model_name='notificationpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
