# Generated by Django 4.2.3 on 2023-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_notificationpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkpost',
            name='created_at',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
