# Generated by Django 4.2.3 on 2023-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_homeworkpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkpost',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
