# Generated by Django 4.2.3 on 2023-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_homeworkpost_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notificationpost',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='../media/uploads'),
        ),
    ]
