name: Auto Merge Frontend to Integrated
on:
  push:
    branches:
      - Frontend

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge Frontend to Integrated
      run: |
        git config user.name "Sarthak Abhijit Rawool"
        git config user.email "sarthakrawool09@gmail.com"
        git checkout Integrated
        git merge Frontend
        git push
